name: Scheduled Redeploy

on:
  schedule:
    # runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp file
        run: echo "Redeployed at $(date)" > last_deploy_time.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_deploy_time.txt
          git commit -m "Automated redeploy $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
