name: Scheduled Redeploy

on:
  schedule:
    - cron: '*/20 * * * *'  # runs every 20 minutes

permissions:
  contents: write

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Trigger empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git reset --hard origin/main
          git commit --allow-empty -m "Scheduled redeploy commit"
          git push origin main --force
